d&dでpdf読み込み機能実装
YHU-team18/Read-files-and-learn-words pull request #17
Opened 2022-06-16 03:18 UTC by nkmrst

ドラックアンドドロップでpdfを読み込みして、そのファイルをformdataに送る作業までしています。
後は、staticというファイルを作成して、その下階層にjs,cssファイルを作成しています。追加の都合上setting.pyのstatic_DIRSを追加して、staticファイルの位置を認識されるように変更させています。

2022-06-16 05:05 UTC, ROBO358 requested changes
確認お願いします🙇

2022-06-16 05:05 UTC, ROBO358 commented on src/static/js/style.js
> +
ここらへんで`#preview`を追加し直すか、下で削除をせずに内容だけクリアする形がいいと思います。

2022-06-16 10:54 UTC, ROBO358 approved these changes
👍

2022-06-16 10:55 UTC, ROBO358 commented
Close #9 
のようにコメントし、Issueとの関連付けを忘れずにお願いします。

2022-06-18 16:46 UTC, hisashi-y approved these changes

2022-06-19 03:11 UTC, makinzm approved these changes
👍

2022-06-19 03:11 UTC, makinzm commented on src/static/js/style.js
> +      // 修士論文の枚数制限→40~120枚程度なので120で計算
slackで回答いただいたため,上記の点大丈夫です!

2022-06-19 03:17 UTC, merged