BoW#6
YHU-team18/Read-files-and-learn-words pull request #20
Opened 2022-06-16 14:29 UTC by hisashi-y

[作業内容]:
- PDFのディレクトリを文字列として受け取り、その中に含まれる英単語について{英単語: 出現回数}の形でカウントを行ったdictionary(BoW)を作成。
- 自分で全て書いた英語テキストを基にテスト用のpdfファイルを二つ作成。
- 二つのファイルに対してBoW生成にかかる時間を計測するテストを実施し、結果をtest_result.txtに保存

2022-06-18 04:28 UTC, makinzm commented
frequencyのファイルをMITライセンスのもので引っ張ってきているため,

https://wisdommingle.com/mit-license/

を参考にreadme作っていただけますと幸いです。

2022-06-18 04:34 UTC, makinzm commented
また,今後もMITライセンスのものをいろいろ引っ張ってくると思うので,
start.shなどがあるファイルにLICENCE.txtなどつけてくださると幸いです.

2022-06-18 04:40 UTC, makinzm commented
先ほどpull request 出したのでLICENCEの確認お願いします.

(reviewerの関係で, pull requestはdeclineしてLICENCE付与していただいても大丈夫です)
(参考: https://qiita.com/medi-y-sato/items/c3d5c357ab020290dccc)

2022-06-18 07:10 UTC, makinzm commented
licenceまだ治してないのでコメントお願い致します。（最後の行）

2022-06-18 07:24 UTC, hisashi-y commented
- LICENCEの最後の行の '<-- ここに使用したリポジトリのURL等を追加 -->'となっているところにリポジトリのurlを記載しました。
- scr/PDFtoBoW にREADME.mdを作成して、今回使用したword frequency dataについての説明をそこに記載しました。

2022-06-18 07:28 UTC, makinzm commented
ありがとうございます！
1. 念のため、リポジトリのファイルも明記していただけると幸いです。（引用元のどのtxtが今回のtxtに対応するか）
1. readmeに書いたcopylightのところをlicenceにもお願いします。ライセンス内の日本語のコメントは削除していただけるますと幸いです。

現在外に出ているため帰宅次第レビュー対応いたします🙇‍♂️

2022-06-18 07:36 UTC, hisashi-y commented
ありがとうございます、対処しておきます！
- LICENSE, README.mdの双方において、記載しているURLをリポジトリ全体ではなく、今回使用したtxtのものに変更
- Copyrightの表記をLICENSEにも追加
- README.mdの文言を少し変更しました

2022-06-18 16:13 UTC, ROBO358 requested changes
一応確認ですが、`sample1.pdf`&`sample2.pdf`は共有OKなものですよね🤔

その他は、以下のとおりです。

2022-06-18 16:13 UTC, ROBO358 commented on src/PDFtoBow/PDFtoBoW.py
> +# nltk.download('omw-1.4')
これは、Docker volumeがリセットされる度に`import`&`download`する必要がある感じですか?

そうであれば、可能なら`import`&`download`されているか判断して自動で`import`&`download`行う処理に変更したほうが良さそう。

2022-06-18 16:27 UTC, hisashi-y commented on src/PDFtoBow/PDFtoBoW.py
> +# nltk.download('omw-1.4')
- sample1.pdfとsample2.pdfは自分ですべて作った英字のテキストをpdfにしたものなので、共有OKなものになっています。

> これは、Docker volumeがリセットされる度にimport&downloadする必要がある感じですか?
- はい、その必要があるので、アドバイスふまえてそのようにやってみようと思います。

2022-06-19 03:00 UTC, makinzm commented
- pathを実行ファイルと相対パスの指定にしたため,どこでも実装できるようにしました.
- Docker_dirのrequiremnts.txtにmoduleを追加しました.

2022-06-19 03:09 UTC, makinzm approved these changes
Review doneです👍

2022-06-19 04:07 UTC, ROBO358 approved these changes
👍

2022-06-19 04:36 UTC, merged