get_BoWが{'単語': 頻度}, {'単語': '辞書のエントリー'}の二つを返すように変更
YHU-team18/Read-files-and-learn-words pull request #28
Opened 2022-06-27 00:15 UTC by hisashi-y

要望を受けてget_BoWの関数において

- {'単語': 頻度}, {'単語': '辞書のエントリー'} の二つのdictを返すように変更しました。
  - この二つのdictを収めたtupleが帰ってくるのではなくて、複数の(2つの)返り値になっています。他の工程において都合が悪ければtupleに形式変更することも可能です。

- 利用した英和辞書のデータについてREADME, LICENSEに記載を追加しました。Public Domain / CC0のものとなっています。
- test.pyにて今回返すようになった{'単語': '辞書のエントリー'}のdictについてjsonで保存、また実際に辞書が作れているかprintで試しています。

2022-06-27 02:22 UTC, ROBO358 requested changes
確認お願いします。

2022-06-27 02:22 UTC, ROBO358 commented on LICENCE
> +https://github.com/kujirahand/EJDict
末尾に空行を追加したい
```suggestion
https://github.com/kujirahand/EJDict

```

2022-06-27 02:22 UTC, ROBO358 commented on src/PDFtoBow/README.md
> +The original data is stored as 'ejdict-hand-utf8.txt'
末尾に空行を追加したい
```suggestion
The original data is stored as 'ejdict-hand-utf8.txt'

```

2022-06-27 02:22 UTC, ROBO358 commented on src/PDFtoBow/test.py
> +print(BoW_meaning1['activity'])
末尾に空行を追加したい
```suggestion
print(BoW_meaning1['activity'])

```

2022-06-27 02:22 UTC, ROBO358 commented on src/PDFtoBow/test.py
> +#     json.dump(BoW_meaning2, f, indent = 4)
それぞれどのような内容のテストなのかコメントがほしい

2022-06-27 05:06 UTC, hisashi-y commented
ありがとうございます。指摘受けて実施しました。
- README.md, LICENSE, test.pyについて末尾に空行を追加しました。
- test.pyでget_BoWの返り値として得た二つのdictをjsonで保存する箇所について、それぞれどんな内容のdictを出力しているかコメントをつけました。

2022-06-27 05:09 UTC, hisashi-y commented
ありがとうございます。コメント受けて実施しました。
空行追加について
- 差分としては表示されているのですが、差分ビューにて各ファイルの行数が増えていないように見えます。実際の編集画面(github上であったり手元のeditor)だと行数が増えて見えるのですがこちら正しく実施できてますでしょうか。

test.pyのjsonの保存の部分のコメントについて
- どのサンプルファイルの、二つあるうちのdictのうちどちらを保存しているかをコメントで記載しました。

2022-06-27 05:29 UTC, hisashi-y commented
- テスト結果を出力する際のファイル名について'サンプルpdfの名前_frequency/meaning.json'という形式に変更しました
- コメントを誤っていたところがあったので修正しました
- 今度こそちゃんと空行を追加できたかと思います

2022-06-28 08:36 UTC, hisashi-y commented
> * 前回までの関数とは別で関数を用意するようお願いします🙇‍♂️
>   
>   * (一緒に挙動を変えたくないので)
> * 元々の辞書をフォークして,辞書を作って参照したい.
この2点について対応しました。
ライセンスについてはリポジトリ直下のファイルにThirdPartyNotices.txtを作成するという方針でいいでしょうか？

2022-06-28 13:59 UTC, ROBO358 approved these changes
👍

2022-06-29 02:32 UTC, makinzm commented
> ライセンスについてはリポジトリ直下のファイルにThirdPartyNotices.txtを作成するという方針でいいでしょうか？

そうですね! 
また別のbranch等でまとめて最後にやりたいと思います!

2022-06-29 02:40 UTC, makinzm approved these changes
👍

2022-06-29 02:41 UTC, merged